services:
  - type: static_site
    name: Zaad Bakery-frontend
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://zaad-bakery.onrender.com/api
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
